version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:${POSTGRES_PORT}
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data/
  web:
    build: .
    command: 'uvicorn main:app --host 0.0.0.0'
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  db-data: